In [1]:
import numpy as np

In [2]:
from numpy.random import randn

In [5]:
rand_array = randn(5,5)

In [6]:
rand_array

array([[-0.50891651, -1.35376493, -1.82848366, -0.15425749,  1.66784009],
       [ 0.25231694, -0.4955117 ,  1.64603796,  0.29910038,  0.17006621],
       [-0.42289837, -1.75643763,  0.02364738,  1.39241516,  0.91619869],
       [ 1.46784571, -1.70094977,  0.61615803, -0.69527919,  0.69921186],
       [-1.01303681,  1.05364022, -1.49941215,  0.05940842,  0.39802642]])

In [9]:
filter_positive = np.where(rand_array<0, 0, rand_array)

In [10]:
filter_positive

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  1.66784009],
       [ 0.25231694,  0.        ,  1.64603796,  0.29910038,  0.17006621],
       [ 0.        ,  0.        ,  0.02364738,  1.39241516,  0.91619869],
       [ 1.46784571,  0.        ,  0.61615803,  0.        ,  0.69921186],
       [ 0.        ,  1.05364022,  0.        ,  0.05940842,  0.39802642]])

In [11]:
A = [1, 3, 5, 6]
B = [100, 200, 300 , 500]
condition = [False , True , True, True]


In [12]:
conditional_array  = np.where(condition, A, B)

In [13]:
conditional_array

array([100,   3,   5,   6])