In [1]:
import numpy as np

In [2]:
np_array = np.array([[1,2,3,4],[8,9,10, 11]])

In [3]:
np_array


array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [4]:
inverse = 1/ np_array

In [5]:
inverse

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [6]:
exp = np_array**2

In [7]:
exp

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [8]:
mult = np_array *2

In [9]:
mult


array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])