In [11]:
import numpy as np


In [12]:
items = [200,500, 20]
people = [[1,0, 2], [1,1,0]]

In [15]:
items = np.array(items)
items = np.transpose(items)

In [19]:
items

array([200, 500,  20])

In [23]:
e = np.arange(6)

In [24]:
e.resize(2,3)

In [26]:
np.transpose(e)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [27]:
e

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
items.size


3

In [29]:
items.T

array([200, 500,  20])

In [30]:
e

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
e.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [32]:
np.matmul(items, people)

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

In [33]:
items.shape


(3,)

In [34]:
people = np.array(people
                 )

In [35]:
people

array([[1, 0, 2],
       [1, 1, 0]])

In [36]:
people.shape

(2, 3)

In [41]:
items = items.reshape(3,1)

In [48]:
each_val=np.matmul([[1,1,1], [1,0,1]], items)

In [49]:
each_val.reshape(1,  2)

array([[720, 220]])

In [51]:
each_val.shape


(2, 1)

In [52]:
each_val

array([[720],
       [220]])

In [53]:
np.sum(each_val)

940